"""empty message

Revision ID: 1d4f5e26ad39
Revises: bc2507fef64
Create Date: 2015-02-21 21:18:46.339785

"""

# revision identifiers, used by Alembic.
revision = '1d4f5e26ad39'
down_revision = 'bc2507fef64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('bitmask', sa.SmallInteger(), nullable=True))
    op.create_unique_constraint('unique_bitmask', 'roles', ['bitmask'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_bitmask', 'roles')
    op.drop_column('roles', 'bitmask')
    ### end Alembic commands ###
