"""empty message

Revision ID: 3280e01482d1
Revises: None
Create Date: 2014-11-27 10:08:38.450315

"""

# revision identifiers, used by Alembic.
revision = '3280e01482d1'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('links')
    op.drop_table('products')
    op.drop_table('organizations')
    op.drop_table('employment')
    op.drop_table('organization_records')
    op.drop_table('organization_keywords')
    op.drop_table('people')
    op.drop_table('operating_hours')
    op.drop_table('organization_sources')
    op.drop_table('contact_points')
    ### end Alembic commands ###


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(),  nullable=False),
    sa.Column('duns', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('dunsPlus4', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('legalName', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('naics', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('cage', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('taxID', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('countryCode', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('addressLocality', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('addressRegion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postalCode', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('streetAddress', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'organizations_pkey'),
    postgresql_ignore_search_path=False
    )

    op.create_table('people',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('givenName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('familyName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'people_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('organization_keywords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], [u'organizations.id'], name=u'organization_keywords_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'organization_keywords_pkey')
    )
    op.create_table('organization_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], [u'organizations.id'], name=u'organization_records_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'organization_records_pkey')
    )
    op.create_table('employment',
    sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], [u'people.id'], name=u'employment_employee_id_fkey'),
    sa.ForeignKeyConstraint(['employer_id'], [u'organizations.id'], name=u'employment_employer_id_fkey')
    )

    op.create_table('organization_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_uid', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('data_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('spider_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], [u'organizations.id'], name=u'organization_sources_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'organization_sources_pkey')
    )

    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'products_pkey')
    )
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('href', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], [u'organizations.id'], name=u'links_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'links_pkey')
    )
    op.create_table('contact_points',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], [u'organizations.id'], name=u'contact_points_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'contact_points_pkey')
    )

    op.create_table('operating_hours',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('closes', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('opens', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('dayOfWeek', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], [u'contact_points.id'], name=u'operating_hours_contact_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'operating_hours_pkey')
    )
    ### end Alembic commands ###
