"""empty message

Revision ID: 36d5893e2b40
Revises: 1c4bc6ad5e4b
Create Date: 2015-02-28 23:50:03.043514

"""

# revision identifiers, used by Alembic.
revision = '36d5893e2b40'
down_revision = '1c4bc6ad5e4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    op.drop_column('invitations', 'created')
    ### end Alembic commands ###
