"""empty message

Revision ID: bc2507fef64
Revises: ed8d2e0b6cf
Create Date: 2015-01-25 21:39:09.987292

"""

# revision identifiers, used by Alembic.
revision = 'bc2507fef64'
down_revision = 'ed8d2e0b6cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=120), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    ### end Alembic commands ###
